### ISSUE TITLE
Gosu fails under Gradle 2.12

### ISSUE THREAD

**Issue by ysb33r** [gosu-lang/gradle-gosu-plugin#21]
The issue is that the Gradle internal API for `DefaultSourceDirectorySet` has been changed adding a third parameter. (The failure is not unique to Gosu pugin - a number of the community language plugins have also been broken).

One suggested fix is the following - https://github.com/ysb33r/gradle-mirah-plugin/blob/master/src/main/groovy/org/ysb33r/gradle/mirah/MirahSourceSet.groovy#L69

**Comment by DPUkyle** [comment]
Yes, unfortunately the Gradle APIs change quite often. Of course they are marked internal so we use them at our own peril!

We will certainly address this in the next release, though it would naturally break backwards compatibility with older Gradle versions :(

The list of known incompatible versions is also posted on the plugin portal [here](https://plugins.gradle.org/plugin/org.gosu-lang.gosu).

**Comment by DPUkyle** [comment]
@ysb33r thank you very much for using the plugin, BTW!

**Comment by ysb33r** [comment]
The link to the code that I posted will maintain compatibility with your current supported Gradle versions.


Sent from my Samsung device

-------- Original message --------
