### ISSUE TITLE
Gradle 4.3 will change API for `CompileOptions`

### ISSUE THREAD

**Issue by bmuschko** [gosu-lang/gradle-gosu-plugin#34]
Just as a heads up: Our smoke tests (which this plugin is part of) indicating that your plugin will break with Gradle 4.3. We deliberately decided to change the API of the internal API `CompileOptions`. It will likely require a change of your plugin code + a new release.

This is failing with version 0.3.0 of your plugin.

**Comment by DPUkyle** [comment]
Thanks @bmuschko. I can confirm the failure locally in my fork of Gradle by running `org.gradle.smoketests.ThirdPartyPluginsSmokeTest`.

Is there a pre-release of Gradle 4.3 I can test against in my CI? I tried giving version `4.3-20171004093631+0000` to testkit but could not reproduce that way.

**Comment by bmuschko** [comment]
The changed in the 4.3 snapshot are still quite a bit in flux. I'd wait for the RC-1. ETA mid next week.

**Comment by lptr** [comment]
@DPUkyle we've made all the changes we planned for `CompileOptions`. Please try again with the latest nightly. Alternatively you can wait until 4.3-rc-1 comes out during the week according to plan.

**Comment by DPUkyle** [comment]
Thanks @bmuschko and @lptr ; I just released v0.3.5 with the fix. I'll create a pull request for gradle/gradle and link it back here.
