### ISSUE TITLE
Gosu plugin depends on Gradle-internal compiler architecture

### ISSUE THREAD

**Issue by lptr** [gosu-lang/gradle-gosu-plugin#39]
The `*CopilerSpec`/`*Compiler` types used in `GosuCompile.java` and elsewhere in the code are not public Gradle APIs. We on the Gradle side are changign these types, which broke the Gosu plugin. If you want to use a similar architecture as used in the Gradle internal APIs, please consider replicating the code in whole. For Gradle 4.8 we've reverted the changes to these internal types to keep Gosu working, but with Gradle 5.0 we will want to make the changes for real, and then the Gosu plugin in its current form will stop working.

**Comment by DPUkyle** [comment]
Thanks @lptr. Yes, I know I was always taking a risk with these `internal` packages. I had been toying with the idea of bundling my own copied implementations of the interfaces so thank you for validating my thinking by suggesting the same. Thanks again for including a third-party test for Gosu and I'll send you a PR after I make the changes to preserve forward compatibility.

**Comment by lptr** [comment]
Great! Thanks for taking care of this @DPUkyle!
